// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjlpYgVk30RIm-oA6cKayyOXa6zJx6OCg',
    appId: '1:318653400334:web:02179de25dafbbc8fb035f',
    messagingSenderId: '318653400334',
    projectId: 'valuation-ffb5d',
    authDomain: 'valuation-ffb5d.firebaseapp.com',
    storageBucket: 'valuation-ffb5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtO_Og_q7uH_Jv6V3LnQYOIXkW8LVY6cE',
    appId: '1:318653400334:android:4c17cadc33bb4f46fb035f',
    messagingSenderId: '318653400334',
    projectId: 'valuation-ffb5d',
    storageBucket: 'valuation-ffb5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl_N_IYdLD8jGMilelB1eKzoEM_ON1XvQ',
    appId: '1:318653400334:ios:c702cadd23007f96fb035f',
    messagingSenderId: '318653400334',
    projectId: 'valuation-ffb5d',
    storageBucket: 'valuation-ffb5d.appspot.com',
    iosBundleId: 'com.example.valuation281024',
  );
}
